### ISSUE TITLE
Unable to tweak code to open RadioDroid app via double click on the RADIO button 

### ISSUE THREAD

**Issue by ojherbst** [g4rb4g3/CtsTestStarter#1]
Hey g4rbag3! First of all, thanks for this little app and the work invested to get to it. I imported your code and played around with it. I am able to change the code and re-map my Ioniq's physical buttons and the clock button, but the 1 button I really want namely the RADIO button (to open RadioDroid via 2x clicks), I can't get to work. I am using "com.lge.ivi.action.KEY_RADIO" but starting to wonder whether the radio key is actually addressed as "KEY_RADIO" by the system? Do you know if this is the correct name? I can start the RadioDroid app (PackageName: net.programmierecke.radiodroid2) from "any" button but not from the radio button. In fact, I can't start anything from there, hence, I think the name must be wrong. Any help is greatly appreciated. Thanks, buddy.

**Comment by g4rb4g3** [comment]
take a look at version 2.0 which allow mapping to any button.
