### ISSUE TITLE
Thanks for your work

### ISSUE THREAD

**Issue by bodybreaker** [g4rb4g3/CtsTestStarter#2]
Thanks for your work!

I saw your post on other forum.

> Whats required to get it working?
First you have to pull the com.lge.ivi.jar & com.lge.ivi.odex library (better the whole (/system/framework folder) from the car.
Then you have to deodex it.
Next you have to convert it back to java (dex2jar is your friend).
Pull repo https://github.com/g4rb4g3/ivireceiver
Put the deodexed and converted com.lge.ivi.jar into ivireceiver\app\externallibs.
Open the project in Android Studio, compile it and let it run!

Do i have to pull com.lge.ivi.jar with SDcard?

**Comment by g4rb4g3** [comment]
Hi, you have to enable ADB on the head unit (network mode not usb).
Then you have to use "adb pull /system/framework/com.lge.ivi.jar" and "adb pull /system/framework/com.lge.ivi.odex" to get the 2 files on your computer.
Then follow the deodex and converting steps you have found already.
For the 191209 firmware I've made a youtube video showing how to enable adb.
https://www.youtube.com/watch?v=zR56ppeuN3s

**Comment by bodybreaker** [comment]
Thank you for your video and description. 
Do you know if i update to newer version of firmware, will it be removed??( installed app, rooting .. etc)

Have a nice day

**Comment by g4rb4g3** [comment]
Only Hyundai/Kia knows that... We will see when the next update arrives.
